apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: staff-backend-hpa
  namespace: staff-management

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staff-backend

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50